### PR TITLE
Implemented default checkbox filter value

### PR DESCRIPTION
**Pull request by IvanBernatovic**
This PR is related to [this ticket](https://github.com/njleonzhang/vue-data-tables/issues/122). I tested it locally for client-side data-tables component and everything worked fine and data is properly filtered by default.

### CODE REVIEW

**Comment by njleonzhang** [comment]
@IvanBernatovic  would you please help to write a unit test?

**Comment by IvanBernatovic** [comment]
@njleonzhang Sure, I'll look into it and let you know more. I intend to work with [this file](https://github.com/njleonzhang/vue-data-tables/blob/master/test/unit/specs/clientVersion/checkFilter.spec.js) which seems is related to checkboxes on client side, I'll also take the opportunity to test it with server side implementation and write unit test for that too.

I'll try to work on it this week. Do you have anything else in mind or do you have any advice/suggestion?

**Comment by njleonzhang** [comment]
@IvanBernatovic You are right. just add unit test in [checkFilter.spec.js](https://github.com/njleonzhang/vue-data-tables/blob/master/test/unit/specs/clientVersion/checkFilter.spec.js) for client side and [checkFilter.spec.js](https://github.com/njleonzhang/vue-data-tables/blob/master/test/unit/specs/clientVersion/checkFilter.spec.js) for server side. 
I have reviewed your code and left a message [here](https://github.com/njleonzhang/vue-data-tables/pull/123/files), please take a look.

**Comment by njleonzhang** [comment]
default checkbox filter is removed in v3.4

**Pull request closed without merging**
