### PR TITLE
Adds optional flag to disable pagination

### LINKED ISSUE #52: Optionally disable pagination
Hi, thanks for the awesome component!

I would like to disable pagination in some cases. I would really like to have something like `has-pagination` property.

Would you mind a PR from me with this feature?

### PR DESCRIPTION
**Pull request by sobolevn**
Changes:
1. Adds new method to the computed properties called `paginationShow`
2. Adds new test to check that pagination does not render when disabled

Closes #52

### CODE REVIEW

**Comment by njleonzhang** [comment]
Tnx, merged.
 I have just changed `expect(jump).to.be.null` to `should.not.exist(jump)`

**Comment by sobolevn** [comment]
@njleonzhang thanks! One more thing that caught my eye.
You are using timeout to test `vue`'s internals. While it is better use `nextTick`: https://vuejs.org/v2/api/#Vue-nextTick

**Comment by njleonzhang** [comment]
Tnx @sobolevn I will preferentially use `nextTick`.

**Comment by pixelpaulaus** [comment]
what about data-tables-server?

**Comment by njleonzhang** [comment]
@pixelpaulaus same to data-tables.

**Pull request merged**
