### PR TITLE
Adding dropdown option 

### PR DESCRIPTION
**Pull request by chandrasekar-zarget**
Adding dropdown option in row action definition which will be helpful to provide more option for vue data table row

### CODE REVIEW

**Comment by FisNew** [comment]
Would you update the Docs?

**Comment by njleonzhang** [comment]
tnx very much, I will check later. :)

**Comment by njleonzhang** [comment]
@chandrasekar-zarget Tnx for your contribution.

First of all, let focus on your PR:
1. Document is not complete. For example, `iconOnly` seems should be removed(in readme and also `en.vue`), `items`'s property is not described. 
2. how handleCommand work when there are more than one item? it only has one param `row`, it can not distinguish which item is clicked.

Secondly, let's talk on another point. 
In this PR, you help to add a Component `dropdown` for action column. It's OK. 
But if customer need other components, we may need to add more and more components. So maybe we need some change. **Make action column customized**, let customer decide what to show in action column. `named slot` can help. You can refer to 9cd9231c1619350b16d57675bd932187bac22f7b and [sample](https://github.com/njleonzhang/vue-data-tables/blob/2.0/play/App.vue#L30). someone need a special component in Tool bar, I make a `named slot` so that he can add anything he want. I think you can do same thing and make custom be able to add anything, not a special component.'
Maybe we should forget this PR and focus on another :)

**Comment by chandrasekar-zarget** [comment]
Hi @njleonzhang thanks for reviewing dropdown option in table. I have forgot to push my latest changes . Here is is my idea that how dropdown going to work. Example code for dropdown with many items

     

    return [{
        mtype: 'dropdown',
        type: 'primary',
        icon: 'fa fa-ellipsis-v',
        iconOnly: true,
        items: [
          {
            name: 'Edit',
            id: '1'
          },
          {
            name: 'Delete',
            id: '2'
          }
        ],
        handleCommand
      }
      ]

as of now element's dropdown item has option called _command_ to identify which menu item got clicked so I reverted handleCommand's parameter row to none . So by default menu item command will be get passed .

el-dropdown(v-if='action.mtype === "dropdown"', @command='action.handleCommand')
              el-button(:type='action.type')
                span(v-if='action.name !== undefined')  {{ action.name }}
                i(:class='action.icon')
              el-dropdown-menu(slot='dropdown')
                el-dropdown-item(v-for='item in action.items', **:command='item.id'** **:passback='row'**)  {{ item.name }}
            el-button(v-if='action.mtype !== "dropdown"', :type='action.type', v-bind='action.buttonProps') {{action.name}}

Another requirement would be which row item got clicked . so I have created an property called passback on element's dropdown item which will just pass object as second parameter to handleCommand.  with Passback property user can send row / any object for hist.

As you mention I will remove iconOnly option.

**Comment by njleonzhang** [comment]
@chandrasekar-zarget Have you read the second point I reminded?

**Comment by chandrasekar-zarget** [comment]
yeah , I got your point I will come with good solution

**Comment by njleonzhang** [comment]
Tnx, please work on branch 2.0

**Pull request closed without merging**
